/**
 * Comprehensive Astrological Reference Data
 */

export const ZODIAC_SIGNS = [
  {
    id: 'aries',
    name: 'Aries',
    symbol: '♈',
    glyphName: 'The Ram',
    dates: 'Mar 21 - Apr 19',
    element: 'Fire',
    modality: 'Cardinal',
    ruler: 'Mars',
    polarity: 'Yang / Masculine',
    color: '#FF4D4D',
    elementColor: 'from-red-500 to-amber-500',
    stone: 'Diamond & Red Jasper',
    luckyNumbers: [1, 9, 18, 27],
    luckyDay: 'Tuesday',
    tarotCard: 'The Emperor (IV)',
    keywords: ['Courageous', 'Pioneering', 'Passionate', 'Direct', 'Spontaneous'],
    strengths: ['Fearless initiative', 'Inspirational vitality', 'Unyielding candor', 'Natural leadership'],
    shadows: ['Impatience', 'Quick-tempered', 'Impulsive risk-taking', 'Difficulty compromising'],
    loveCompatibility: {
      high: ['Leo', 'Sagittarius', 'Gemini', 'Aquarius'],
      moderate: ['Libra', 'Aries'],
      challenging: ['Cancer', 'Capricorn'],
    },
    careers: ['Entrepreneur', 'Athlete', 'Surgeon', 'Military / First Responder', 'Creative Director'],
    mythology: 'Represented by the golden-fleeced ram Chrysomallos, which carried Phrixus to Colchis. Commemorated by Zeus among the stars as a symbol of divine courage and rescue.',
    summary: 'Aries is the first sign of the zodiac, symbolizing the spark of creation, courage, and raw life force. They meet existence head-on with an infectious zeal for breakthrough adventures.',
  },
  {
    id: 'taurus',
    name: 'Taurus',
    symbol: '♉',
    glyphName: 'The Bull',
    dates: 'Apr 20 - May 20',
    element: 'Earth',
    modality: 'Fixed',
    ruler: 'Venus',
    polarity: 'Yin / Feminine',
    color: '#10B981',
    elementColor: 'from-emerald-500 to-teal-500',
    stone: 'Emerald & Rose Quartz',
    luckyNumbers: [2, 6, 15, 24],
    luckyDay: 'Friday',
    tarotCard: 'The Hierophant (V)',
    keywords: ['Steadfast', 'Sensual', 'Patient', 'Loyal', 'Artistic'],
    strengths: ['Unshakable dependability', 'Financial mastery', 'Refined aesthetic taste', 'Calm endurance'],
    shadows: ['Stubbornness', 'Resistance to change', 'Material possessiveness', 'Sensory overindulgence'],
    loveCompatibility: {
      high: ['Virgo', 'Capricorn', 'Cancer', 'Pisces'],
      moderate: ['Scorpio', 'Taurus'],
      challenging: ['Leo', 'Aquarius'],
    },
    careers: ['Architect', 'Financial Advisor', 'Chef / Restaurateur', 'Landscape Designer', 'Art Appraiser'],
    mythology: 'Connected to the Cretan Bull captured by Heracles and the white bull form assumed by Zeus to court Europa, celebrating the grounded majesty and fertility of nature.',
    summary: 'Taurus is the great builder and preserver of the zodiac, grounded in tangible reality and sensory grace. They cultivate lasting sanctuaries where beauty and abundance flourish.',
  },
  {
    id: 'gemini',
    name: 'Gemini',
    symbol: '♊',
    glyphName: 'The Twins',
    dates: 'May 21 - Jun 20',
    element: 'Air',
    modality: 'Mutable',
    ruler: 'Mercury',
    polarity: 'Yang / Masculine',
    color: '#F59E0B',
    elementColor: 'from-amber-400 to-yellow-500',
    stone: 'Agate & Citrine',
    luckyNumbers: [3, 5, 14, 23],
    luckyDay: 'Wednesday',
    tarotCard: 'The Lovers (VI)',
    keywords: ['Curious', 'Witty', 'Adaptable', 'Articulate', 'Versatile'],
    strengths: ['Intellectual agility', 'Charming communication', 'Fast social rapport', 'Multi-tasking wizardry'],
    shadows: ['Restlessness', 'Nervous tension', 'Superficial focus', 'Indecision'],
    loveCompatibility: {
      high: ['Libra', 'Aquarius', 'Aries', 'Leo'],
      moderate: ['Sagittarius', 'Gemini'],
      challenging: ['Virgo', 'Pisces'],
    },
    careers: ['Journalist', 'Software Engineer', 'Translator', 'Marketing Strategist', 'Author / Speaker'],
    mythology: 'Castor and Pollux, the inseparable Dioscuri twins of Greek mythology—one mortal, one immortal—granted eternal brotherhood in the celestial heavens by Zeus.',
    summary: 'Gemini bridges ideas and perspectives with brilliant intellectual agility. Driven by an insatiable curiosity, they thrive at the crossroads where diverse minds converge.',
  },
  {
    id: 'cancer',
    name: 'Cancer',
    symbol: '♋',
    glyphName: 'The Crab',
    dates: 'Jun 21 - Jul 22',
    element: 'Water',
    modality: 'Cardinal',
    ruler: 'Moon',
    polarity: 'Yin / Feminine',
    color: '#60A5FA',
    elementColor: 'from-blue-400 to-cyan-500',
    stone: 'Moonstone & Pearl',
    luckyNumbers: [2, 7, 11, 25],
    luckyDay: 'Monday',
    tarotCard: 'The Chariot (VII)',
    keywords: ['Intuitive', 'Nurturing', 'Protective', 'Empathetic', 'Devoted'],
    strengths: ['Psychic empathy', 'Maternal/paternal dedication', 'Emotional wisdom', 'Deep memory & loyalty'],
    shadows: ['Moodiness', 'Defensive retreat', 'Clinging to past grievances', 'Over-protectiveness'],
    loveCompatibility: {
      high: ['Scorpio', 'Pisces', 'Taurus', 'Virgo'],
      moderate: ['Capricorn', 'Cancer'],
      challenging: ['Aries', 'Libra'],
    },
    careers: ['Psychotherapist', 'Pediatrician', 'Interior Architect', 'Historian', 'Hospitality Director'],
    mythology: 'The brave giant crab Karkinos dispatched by Hera to aid the Hydra against Heracles, rewarded for its fierce devotion with a consecrated place in the cosmos.',
    summary: 'Cancer guards the sacred sanctuaries of heart, family, and subconscious memory. Guided by lunar tides, they possess boundless empathy and fierce protective loyalty.',
  },
  {
    id: 'leo',
    name: 'Leo',
    symbol: '♌',
    glyphName: 'The Lion',
    dates: 'Jul 23 - Aug 22',
    element: 'Fire',
    modality: 'Fixed',
    ruler: 'Sun',
    polarity: 'Yang / Masculine',
    color: '#F59E0B',
    elementColor: 'from-amber-500 to-orange-500',
    stone: 'Ruby & Peridot',
    luckyNumbers: [1, 4, 10, 19],
    luckyDay: 'Sunday',
    tarotCard: 'Strength (VIII)',
    keywords: ['Radiant', 'Generous', 'Charismatic', 'Noble', 'Creative'],
    strengths: ['Inspiring presence', 'Heartfelt generosity', 'Artistic brilliance', 'Loyal guardianship'],
    shadows: ['Excessive pride', 'Need for constant applause', 'Domineering demeanor', 'Dramatization'],
    loveCompatibility: {
      high: ['Aries', 'Sagittarius', 'Gemini', 'Libra'],
      moderate: ['Aquarius', 'Leo'],
      challenging: ['Taurus', 'Scorpio'],
    },
    careers: ['Actor / Performer', 'Creative Executive', 'Motivational Speaker', 'Filmmaker', 'High-End Brand Designer'],
    mythology: 'The fearsome Nemean Lion slain by Heracles in his first labor, whose golden, impenetrable hide was elevated to the heavens as a testament to indomitable courage.',
    summary: 'Leo radiates with the boundless vitality and warmth of the Sun. They inspire the world through authentic creative self-expression, magnanimous generosity, and sovereign dignity.',
  },
  {
    id: 'virgo',
    name: 'Virgo',
    symbol: '♍',
    glyphName: 'The Maiden',
    dates: 'Aug 23 - Sep 22',
    element: 'Earth',
    modality: 'Mutable',
    ruler: 'Mercury',
    polarity: 'Yin / Feminine',
    color: '#10B981',
    elementColor: 'from-teal-500 to-emerald-600',
    stone: 'Sapphire & Amazonite',
    luckyNumbers: [5, 14, 23, 32],
    luckyDay: 'Wednesday',
    tarotCard: 'The Hermit (IX)',
    keywords: ['Analytical', 'Devoted', 'Methodical', 'Discerning', 'Healing'],
    strengths: ['Precision craft', 'Selfless service', 'Problem-solving genius', 'Integrity & ethics'],
    shadows: ['Perfectionism', 'Over-critical thinking', 'Anxiety & worry', 'Self-criticism'],
    loveCompatibility: {
      high: ['Taurus', 'Capricorn', 'Cancer', 'Scorpio'],
      moderate: ['Pisces', 'Virgo'],
      challenging: ['Gemini', 'Sagittarius'],
    },
    careers: ['Data Scientist', 'Medical Specialist', 'Editor', 'Holistic Nutritionist', 'System Architect'],
    mythology: 'Astraea, the virgin goddess of innocence and justice, the last immortal to live among humans during the Golden Age before ascending to the stars.',
    summary: 'Virgo is the sacred craftsman and healer of the zodiac, dedicated to refining systems, nourishing wellness, and bringing quiet excellence to every detail of life.',
  },
  {
    id: 'libra',
    name: 'Libra',
    symbol: '♎',
    glyphName: 'The Scales',
    dates: 'Sep 23 - Oct 22',
    element: 'Air',
    modality: 'Cardinal',
    ruler: 'Venus',
    polarity: 'Yang / Masculine',
    color: '#EC4899',
    elementColor: 'from-pink-500 to-rose-400',
    stone: 'Opal & Lapis Lazuli',
    luckyNumbers: [6, 15, 24, 33],
    luckyDay: 'Friday',
    tarotCard: 'Justice (XI)',
    keywords: ['Diplomatic', 'Harmonious', 'Charming', 'Just', 'Aesthetic'],
    strengths: ['Uncanny fairness', 'Aesthetic refinement', 'Peacemaking diplomacy', 'Partnership synergy'],
    shadows: ['Indecision', 'Conflict avoidance', 'People-pleasing', 'Superficial compromises'],
    loveCompatibility: {
      high: ['Gemini', 'Aquarius', 'Leo', 'Sagittarius'],
      moderate: ['Aries', 'Libra'],
      challenging: ['Cancer', 'Capricorn'],
    },
    careers: ['Diplomat / Lawyer', 'Art Director', 'Mediator', 'Fashion Stylist', 'Interior Designer'],
    mythology: 'The golden scales of balance held aloft by Themis and Astraea, symbolizing the universal equilibrium, moral order, and objective truth in the universe.',
    summary: 'Libra seeks harmonious equilibrium and beauty in all realms. Master diplomats and lovers of art, they create bridges of empathy and elegant consensus wherever they walk.',
  },
  {
    id: 'scorpio',
    name: 'Scorpio',
    symbol: '♏',
    glyphName: 'The Scorpion & Phoenix',
    dates: 'Oct 23 - Nov 21',
    element: 'Water',
    modality: 'Fixed',
    ruler: 'Pluto & Mars',
    polarity: 'Yin / Feminine',
    color: '#8B5CF6',
    elementColor: 'from-purple-600 to-indigo-800',
    stone: 'Topaz & Obsidian',
    luckyNumbers: [8, 11, 18, 22],
    luckyDay: 'Tuesday',
    tarotCard: 'Death (XIII) - Transformation',
    keywords: ['Magnetic', 'Transformative', 'Intuitive', 'Intense', 'Resilient'],
    strengths: ['Piercing psychological insight', 'Unbreakable resilience', 'Fierce loyalty', 'Alchemical rebirth'],
    shadows: ['Suspicion & paranoia', 'Vindictiveness', 'Desire to control', 'Extreme secretiveness'],
    loveCompatibility: {
      high: ['Cancer', 'Pisces', 'Virgo', 'Capricorn'],
      moderate: ['Taurus', 'Scorpio'],
      challenging: ['Leo', 'Aquarius'],
    },
    careers: ['Investigative Journalist', 'Psychiatrist', 'Forensic Analyst', 'Cybersecurity Lead', 'Crisis Strategist'],
    mythology: 'The celestial scorpion sent by Gaia to subdue Orion, honoring the sacred balance of primal forces and the mystery of death leading to evolutionary rebirth.',
    summary: 'Scorpio embodies the alchemical power of transformation. Penetrating superficial illusions, they navigate emotional depths with unshakeable courage and rise triumphant from every ashes.',
  },
  {
    id: 'sagittarius',
    name: 'Sagittarius',
    symbol: '♐',
    glyphName: 'The Archer & Centaur',
    dates: 'Nov 22 - Dec 21',
    element: 'Fire',
    modality: 'Mutable',
    ruler: 'Jupiter',
    polarity: 'Yang / Masculine',
    color: '#6366F1',
    elementColor: 'from-indigo-500 to-purple-500',
    stone: 'Turquoise & Tanzanite',
    luckyNumbers: [3, 9, 12, 21],
    luckyDay: 'Thursday',
    tarotCard: 'Temperance (XIV)',
    keywords: ['Expansive', 'Philosophical', 'Adventurous', 'Candid', 'Optimistic'],
    strengths: ['Visionary idealism', 'Contagious optimism', 'Deep philosophical quest', 'Cultural adaptability'],
    shadows: ['Tactlessness', 'Restlessness', 'Overpromising', 'Dogmatic superiority'],
    loveCompatibility: {
      high: ['Aries', 'Leo', 'Libra', 'Aquarius'],
      moderate: ['Gemini', 'Sagittarius'],
      challenging: ['Virgo', 'Pisces'],
    },
    careers: ['Philosopher / Professor', 'Foreign Correspondent', 'Travel Documentarian', 'Publisher', 'International Diplomat'],
    mythology: 'Chiron the noble centaur, mentor to Greece’s greatest heroes and master of medicine, astrology, and music, placed in the stars as a teacher of divine wisdom.',
    summary: 'Sagittarius aims their celestial arrow at the highest truths and farthest horizons. Driven by Jupiterian optimism, they seek cosmic meaning through exploration, humor, and philosophy.',
  },
  {
    id: 'capricorn',
    name: 'Capricorn',
    symbol: '♑',
    glyphName: 'The Sea-Goat',
    dates: 'Dec 22 - Jan 19',
    element: 'Earth',
    modality: 'Cardinal',
    ruler: 'Saturn',
    polarity: 'Yin / Feminine',
    color: '#059669',
    elementColor: 'from-emerald-700 to-teal-800',
    stone: 'Garnet & Onyx',
    luckyNumbers: [4, 8, 13, 22],
    luckyDay: 'Saturday',
    tarotCard: 'The Devil (XV) - Mastery of Matter',
    keywords: ['Ambitious', 'Disciplined', 'Masterful', 'Pragmatic', 'Enduring'],
    strengths: ['Strategic longevity', 'Unrivaled work ethic', 'Executive leadership', 'Sovereign integrity'],
    shadows: ['Pessimism', 'Emotional coldness', 'Hyper-materialism', 'Fear of vulnerability'],
    loveCompatibility: {
      high: ['Taurus', 'Virgo', 'Scorpio', 'Pisces'],
      moderate: ['Cancer', 'Capricorn'],
      challenging: ['Aries', 'Libra'],
    },
    careers: ['CEO / Executive', 'Judge / Legal Scholar', 'Civil Engineer', 'Financial Director', 'Asset Manager'],
    mythology: 'Pricus, the mythological immortal sea-goat favored by Chronos, whose climbing from the watery depths of emotion to the mountaintops of mastery represents the climb of the human soul.',
    summary: 'Capricorn scales the highest peaks of achievement with relentless discipline and ancient wisdom. They construct lasting foundations, demonstrating that patience transforms stones into empires.',
  },
  {
    id: 'aquarius',
    name: 'Aquarius',
    symbol: '♒',
    glyphName: 'The Water-Bearer',
    dates: 'Jan 20 - Feb 18',
    element: 'Air',
    modality: 'Fixed',
    ruler: 'Uranus & Saturn',
    polarity: 'Yang / Masculine',
    color: '#06B6D4',
    elementColor: 'from-cyan-500 to-blue-600',
    stone: 'Amethyst & Labradorite',
    luckyNumbers: [7, 11, 22, 29],
    luckyDay: 'Saturday',
    tarotCard: 'The Star (XVII)',
    keywords: ['Visionary', 'Humanitarian', 'Eccentric', 'Original', 'Independent'],
    strengths: ['Futuristic foresight', 'Radical authenticity', 'Humanitarian passion', 'Unconventional genius'],
    shadows: ['Emotional aloofness', 'Contrarian rebellion', 'Impersonal detachment', 'Stubborn dogma'],
    loveCompatibility: {
      high: ['Gemini', 'Libra', 'Aries', 'Sagittarius'],
      moderate: ['Leo', 'Aquarius'],
      challenging: ['Taurus', 'Scorpio'],
    },
    careers: ['AI Researcher', 'Humanitarian Director', 'Aerospace Engineer', 'Astrologer / Futurist', 'Social Innovator'],
    mythology: 'Ganymede, the divine cupbearer who pours the cosmic waters of knowledge and spiritual illumination upon mankind from the jar of the gods.',
    summary: 'Aquarius pours the waters of innovation and cosmic knowledge for the advancement of all humanity. Maverick thinkers and rebels with a cause, they inhabit tomorrow today.',
  },
  {
    id: 'pisces',
    name: 'Pisces',
    symbol: '♓',
    glyphName: 'The Two Fishes',
    dates: 'Feb 19 - Mar 20',
    element: 'Water',
    modality: 'Mutable',
    ruler: 'Neptune & Jupiter',
    polarity: 'Yin / Feminine',
    color: '#8B5CF6',
    elementColor: 'from-indigo-400 to-purple-600',
    stone: 'Aquamarine & Fluorite',
    luckyNumbers: [3, 7, 12, 16],
    luckyDay: 'Thursday',
    tarotCard: 'The Moon (XVIII)',
    keywords: ['Compassionate', 'Mystical', 'Artistic', 'Intuitive', 'Dreamy'],
    strengths: ['Boundaryless empathy', 'Transcendent artistic talent', 'Spiritual clairvoyance', 'Unconditional love'],
    shadows: ['Escapism', 'Weak psychological boundaries', 'Martyr / victim complex', 'Confusion in practical matters'],
    loveCompatibility: {
      high: ['Cancer', 'Scorpio', 'Taurus', 'Capricorn'],
      moderate: ['Virgo', 'Pisces'],
      challenging: ['Gemini', 'Sagittarius'],
    },
    careers: ['Composer / Musician', 'Spiritual Counselor', 'Poet / Novelist', 'Marine Biologist', 'Visual Artist'],
    mythology: 'Aphrodite and Eros transforming into two intertwined fish to escape the monster Typhon, tied with a golden cord so they would never lose each other in cosmic ocean depths.',
    summary: 'Pisces is the final sign of the zodiac, encompassing the spiritual essence of all twelve. Fluid, poetic, and infinitely compassionate, they dissolve barriers between heart and cosmos.',
  },
];

export const ELEMENTS_METADATA = {
  Fire: {
    color: 'from-red-500 to-amber-500',
    signs: ['Aries', 'Leo', 'Sagittarius'],
    essence: 'Energy, passion, inspiration, creative impulse, and bold forward action.',
    chakra: 'Solar Plexus & Sacral',
  },
  Earth: {
    color: 'from-emerald-500 to-teal-500',
    signs: ['Taurus', 'Virgo', 'Capricorn'],
    essence: 'Physical mastery, grounding, endurance, tangible manifestation, and sensory sanctuary.',
    chakra: 'Root & Heart',
  },
  Air: {
    color: 'from-cyan-400 to-sky-500',
    signs: ['Gemini', 'Libra', 'Aquarius'],
    essence: 'Intellect, communication, conceptual connections, objectivity, and visionary exchange.',
    chakra: 'Throat & Third Eye',
  },
  Water: {
    color: 'from-blue-500 to-indigo-600',
    signs: ['Cancer', 'Scorpio', 'Pisces'],
    essence: 'Emotional depth, intuitive resonance, psychic bonding, and soul-level healing.',
    chakra: 'Sacral & Crown',
  },
};
